server:
  port: 8888
# 连接四大参数
spring:
  datasource:
    url: jdbc:mysql:///user?characterEncoding=utf8&useSSL=true
    username: root
    password: 123
    hikari:
      max-lifetime: 28830000 # 一个连接的生命时长（毫秒），超时而且没被使用则被释放（retired），缺省:30分钟，建议设置比数据库超时时长少30秒，参考MySQL wait_timeout参数（show variables like '%timeout%';）
      maximum-pool-size: 9 # 连接池中允许的最大连接数。缺省值：10；推荐的公式：((core_count * 2) + effective_spindle_count)
  thymeleaf:
    cache: false

  # mybatis 别名扫描
mybatis: type-aliases-package=com.user.pojo

  # mapper.xml文件位置,如果没有映射文件，请注释掉
#  mybatis.mapper-locations=classpath:mappers/*.xml

